Versioning, syncing and disabling ledger for incompatible versions
ClassicLootManager/ClassicLootManager pull request #65
Opened 2021-06-30 19:30 UTC by lantisnt

2021-07-05 12:47 UTC, lantisnt commented
I'm also wondering if there should be a separate field for Ledger version for sync disabling or when we would want to break the sync it would be better to update MAJOR ?

2021-07-07 13:52 UTC, SamMousa commented
>  when we would want to break the sync it would be better to update MAJOR

I think we should connect sync to MAJOR version. Since any backwards incompatible change is also a good reason to not communicate with older versions...

2021-07-07 13:57 UTC, SamMousa requested changes
I think a cleaner approach with respect to function visibility is to start out making every new function local and then only making public what is used by other modules.

2021-07-07 13:57 UTC, SamMousa commented on Modules/VersionManager/VersionManager.lua
> +function VersionManager:HandleIncomingMessage(message, distribution, sender)
this should be a local function

2021-07-07 13:57 UTC, SamMousa commented on Modules/VersionManager/VersionManager.lua
> +function VersionManager:OutOfDate(version, disable)
this should be a local function

2021-07-07 13:57 UTC, SamMousa commented on Modules/VersionManager/VersionManager.lua
> +function VersionManager:HandleAnnounceVersion(data, sender)
Make this a local function and use an actual function reference in your map of handlers (instead of a string)

2021-07-07 13:57 UTC, SamMousa commented on Modules/VersionManager/VersionManager.lua
> +function VersionManager:HandleRequestVersion(data, sender)
Make this a local function and use an actual function reference in your map of handlers (instead of a string)

2021-07-07 13:57 UTC, SamMousa commented on Modules/VersionManager/VersionManager.lua
> +function VersionManager:AnnounceVersion()
Should be a local function

2021-07-10 05:49 UTC, merged